### ISSUE TITLE
[docs] atualizar as instruções para carregar o dump do db usando Docker

### ISSUE THREAD

**Issue by Dan-Mqs** [SOS-RS/backend#109]
Fala, pessoal.

Sou do front, e fui rodar o back localmente com Docker.

Toda a parte de subir o container deu certo, mas as atuais instruções pra carregar o dump do database não funcionam.

Notei que tem alguns PRs abertos que tratam do assunto: #91, #84, #75, #66, #64 

Pra mim, os comandos do #84 funcionaram de primeira. 

PS.: abri issue pois não vi nenhuma issue aberta ou fechada em relação a isso

**Comment by gabrielbrise** [comment]
Opa, passei pelo mesmo mas consegui, vou fazer um PR para atualizar os docs. Por enquanto, se quiser saber o que está dando errado, é que o primeiro comando está escrito errado como se copia um arquivo para o docker.

O comando certo é

```docker cp PATH_TO_SQL_DUMP DOCKER_CONTAINER_ID:/tmp/backup.sql```

Estando com o terminal dentro da pasta do backend, o meu comando ficou assim (o seu ID de container não será o mesmo)

```docker cp ./prisma/dev_dump.sql 0e536f047d0f:/tmp/backup.sql```

**Comment by gabrielbrise** [comment]
Criei um pr aqui https://github.com/SOS-RS/backend/pull/110

**Comment by lucaskdc** [comment]
> Criei um pr aqui #110

Boa proatividade, mas vamos tratar dos PRs em aberto.
Aparentemente o #84 é suficiente para documentar os comandos manualmente.
Com ele aprovado, #110, #91 e #64 podem ser fechados.

**Comment by lucaskdc** [comment]
Tudo resolvido, aparentemente. issue pode ser fechada, correto?

**Comment by Dan-Mqs** [comment]
Boa, tudo resolvido no PR #84. Fechando a issue, obrigado a todos.
