### ISSUE TITLE
Substituir o npm pelo pnpm

### ISSUE THREAD

**Issue by edilson** [SOS-RS/backend#119]
De acordo com os [benchmarks do pnpm](https://pnpm.io/pt/benchmarks) o build da aplicação seria mais rápido se o usássemos. Acredito que com isso o deploy da aplicação seria mais rápido.

**Comment by ocsoares** [comment]
> De acordo com os [benchmarks do pnpm](https://pnpm.io/pt/benchmarks) o build da aplicação seria mais rápido se o usássemos. Acredito que com isso o deploy da aplicação seria mais rápido.

Eu prefiro o pnpm em desenvolvimento por ser muito mais rápido ao instalar as bibliotecas, mas não acho que isso teria algum impacto significativo no deploy

**Comment by NedcloarBR** [comment]
Já eu curto o [Yarn Pnp](https://yarnpkg.com/features/pnp)
mas no momento do projeto não vejo o porque mudar o gerenciador de pacotes

**Comment by rodrigooler** [comment]
> De acordo com os [benchmarks do pnpm](https://pnpm.io/pt/benchmarks) o build da aplicação seria mais rápido se o usássemos. Acredito que com isso o deploy da aplicação seria mais rápido.

Agradeço pela sugestão de utilizar o pnpm. No entanto, acredito que, neste momento, a troca não traria ganhos significativos para o nosso fluxo de trabalho.
