### ISSUE TITLE
Quando o abrigo aceita pets, habilitar quantidade de vagas e capacidade para pets

### ISSUE THREAD

**Issue by giggio** [SOS-RS/backend#142]
# TL;DR

Na edição do abrigo, atualmente é possível atualizar o número de pessoas abrigadas e se o abrigo aceita pets, porém não é possível cadastrar quantas vagas para pets existem.

![image](https://github.com/SOS-RS/frontend/assets/334958/32d8a808-b674-4137-9c4e-9e4d2c2b6794)

Issue no frontend: https://github.com/SOS-RS/frontend/issues/259

# Problema

<aside>
🗣️ **User story:** Eu sou voluntário. Eu estou tentando atualizar as informações sobre os abrigos. Mas não consigo atualizar os dados de abrigos de pets porque a plataforma não contempla esse dado o que faz com que a informação fique incompleta.

</aside>

# Requisitos

## Tela de edição completa para usuário autenticado

Esta implementação não deve ser feita na tela de edição disponível para qualquer usuário. Apenas na tela de edição para usuário autenticado.

- Mostrar switch para “Aceita pets”
- Ao ligar o switch mostrar os campos:
    - Capacidade de pets do abrigo
    - Quantidade de pets abrigados
- Ao tocar em “Atualizar” salvar no BD os dados inputados pele pessoa usuária.

## Página de detalhe

**Comment by morella12** [comment]
Gostaria de contribuir com esse item

**Comment by rhuam** [comment]
Temos duas soluções para esse item, ambas bem parecidas: #126  e #166 @SOS-RS/backenders

**Comment by larissapissurno** [comment]
update: abri uma thread para conversarmos sobre o conflito de soluções https://discord.com/channels/1237553809371299950/1247269469236236359

**Comment by larissapissurno** [comment]
update: foi decidido na thread the iremos seguir com a solução #126

**Comment by larissapissurno** [comment]
update: 

- PR de back-end mergeado: https://github.com/SOS-RS/backend/pull/126
- PR de front-end aguardando resolução de conflitos: https://github.com/SOS-RS/frontend/pull/206
