### ISSUE TITLE
Rebaixamento de Urgência de Itens

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/backend#143]
Precisamos garantir que itens de necessidade marcados como "precisa - urgente" sejam rebaixados para "precisa - não urgente" após 4 horas, para que a urgência dos itens seja atualizada automaticamente.

**Problema**

**User story:** Eu sou um administrador. Eu estou tentando manter a prioridade correta dos itens de necessidade. Mas itens que são adicionados como "precisa - urgente" permanecem assim por muito tempo, mesmo quando sua urgência já passou, o que dificulta a gestão correta das prioridades.

É essencial que o sistema automaticamente atualize a urgência dos itens, garantindo que os administradores possam ver uma lista precisa e atualizada das necessidades mais urgentes.

**Critérios para aceitação**
- Itens marcados como "precisa - urgente" por mais de 4 horas devem ser automaticamente rebaixados para "precisa - não urgente".
- Um hook no Node.js deve ser implementado para validar o estado dos itens a cada consulta.
- O sistema deve registrar uma atualização no histórico do item indicando a mudança de estado.

**Comment by richhh7g** [comment]
Ta disponível essa task?

**Comment by BertBR** [comment]
> Ta disponível essa task?

Creio que sim. Ninguém moveu ainda e não tem nenhum comentário sobre refinamento ou dúvidas. Quer ajuda pra fazer ela? Podemos trabalhar em paralelo se quiser.

**Comment by luizpbello** [comment]
estou fazendo algo parecido na remoção de itens aqui: https://github.com/SOS-RS/backend/pull/157

**Comment by richhh7g** [comment]
> Creio que sim. Ninguém moveu ainda e não tem nenhum comentário sobre refinamento ou dúvidas. Quer ajuda pra fazer ela? Podemos trabalhar em paralelo se quiser.

Boa, podemos fazer sim! Vou te chamar la no Discord
