### ISSUE TITLE
Remoção de Itens Antigos

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/backend#144]
Precisamos garantir que itens com mais de 48 horas em "precisa - não urgente" ou "disponível para doação" sejam apagados automaticamente para manter a base de dados limpa e atualizada.

**Problema**

**User story:** Eu sou um administrador. Eu estou tentando manter a lista de necessidades atualizada. Mas muitos itens permanecem na lista sem necessidade após 48 horas, o que polui a base de dados e dificulta a visualização das necessidades reais.

É crucial que o sistema automaticamente apague itens desnecessários após 48 horas, garantindo que a base de dados seja limpa e precisa.

Critérios para aceitação
- Itens em "precisa - não urgente" ou "disponível para doação" por mais de 48 horas devem ser automaticamente apagados.
- Um hook no Node.js deve ser implementado para validar o estado dos itens a cada consulta.
- O sistema deve registrar a remoção no histórico do sistema para fins de auditoria.

**Comment by diegodario88** [comment]
Obs: depende da https://github.com/SOS-RS/backend/issues/146

**Comment by luizpbello** [comment]
acabei de enviar uma PR pra essa issue:

https://github.com/SOS-RS/backend/pull/157

**Comment by g42puts** [comment]
Importante que todos usuários responsáveis pela atualização dos itens, sejam comunicados dessa atualização antes de ser implementada, para que dores de cabeça sejam evitadas.

Uma possibilidade é colocar um na parte superior do Abrigo ou um pop-up, apenas para os usuários cadastrados, com 24h de antecedência.
