### ISSUE TITLE
Filtro Simultâneo de "Precisa" e "Necessita Urgente"

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/backend#145]
Precisamos permitir que o usuário selecione simultaneamente os filtros "Precisa" e "Necessita Urgente" ao buscar itens, para que possam visualizar todas as necessidades de forma combinada.

**Problema**

**User story:** Eu sou um voluntário. Eu estou tentando encontrar rapidamente itens que são necessários e urgentes. Mas o sistema atual não permite filtrar ambos simultaneamente, o que dificulta minha capacidade de identificar e priorizar os itens mais críticos.

É essencial que o sistema permita a seleção de múltiplos filtros para fornecer uma visão mais completa das necessidades, melhorando a eficiência do processo de identificação e priorização dos itens necessários.

Critérios para aceitação
- O sistema deve permitir a seleção simultânea dos filtros "Precisa" e "Necessita Urgente".
- A interface de usuário deve oferecer multi seleção ou opções que possibilitem a combinação desses filtros.
- O sistema deve manter a capacidade de filtrar por cada critério individualmente, além da combinação dos dois.
- O sistema deve fornecer uma indicação visual clara de quais filtros estão atualmente aplicados.

**Comment by barbiebrega** [comment]
@rhuam isso seria implementado na modal de filtros?

**Comment by diegodario88** [comment]
no backend acredito que devemos alterar o serviço que  atende o endpoint `/shelters`.  Talvez um ajuste no   `SearchSchema` para que seja possível aceitar uma lista de argumentos no queryParams de prioridade.
``` 
priority=10,20,30
``` 

Mas sim, no frontend isso irá requerer um ajuste no modal de filtros

**Comment by barbiebrega** [comment]
Um select com checkbox dentro soluciona?


![Image](https://github.com/SOS-RS/backend/assets/5641363/29150346-4a10-4390-9f84-fff1a4bc74ba)

**Comment by Brilhante29** [comment]
Boa noite, alguém já está implementando no backend? Posso ficar responsável!

**Comment by diegodario88** [comment]
@barbiebrega 

![image](https://github.com/SOS-RS/backend/assets/25825145/d51a68fd-e813-43e9-b2cb-bf9b8a111b00)

acredito que daria para se basear nesse

**Comment by barbiebrega** [comment]
Ah beleza, acho que pode ser esse sim.
Apenas acrescentem um Help text "Selecione uma ou mais opções" pra ficar mais explícito.

**Comment by rhuam** [comment]
@diegodario88 pode linkar o PR de frontend aqui?

**Comment by diegodario88** [comment]
@barbiebrega a parte do frontend você teve progresso?

**Comment by diegodario88** [comment]
> @diegodario88 pode linkar o PR de frontend aqui?

Segue o link do PR no frontend
https://github.com/SOS-RS/frontend/pull/330

**Comment by HbLuca** [comment]
@larissapissurno de acordo.
Ao realizar o teste no Centro Humanista e ir adicionando itens que necessita com urgencia, necessita ou pode realizar a doacao, estao aparecendo conforme parte de filtro.
Vide Loom:
https://www.loom.com/share/04d848031ab14fd2a66c8eecd150515b?sid=32f53f13-316a-4535-ba02-7e5e49577d60
