### ISSUE TITLE
Histórico de Modificações dos Itens do Abrigo

### ISSUE THREAD

**Issue by rhuam** [SOS-RS/backend#146]
História de Usuário: Como administrador do sistema, quero que cada atualização em um item seja registrada em uma tabela específica de logs, contendo detalhes como item, abrigo, prioridade anterior e atual, data e hora da atualização, IP do solicitante, e se autenticado, o id do usuário para manter um histórico detalhado das mudanças para auditoria e monitoramento.

Critérios de Aceitação:

- Criar uma nova tabela chamada item_updates_log.
- Sempre que um item for atualizado, inserir um novo registro nesta tabela contendo: nome do item, nome do abrigo, prioridade anterior, prioridade atual, data e hora da atualização, IP do usuário e ID de usuário que fez a atualização.
- Assegurar que cada log capture todas as informações necessárias sem falhas.
- Os registros na tabela de logs devem ser imutáveis para manter a integridade dos dados de auditoria.

**Definition of Done (DoD):**

- Código desenvolvido seguindo as melhores práticas de segurança e desempenho conforme os padrões da equipe.
- Funcionalidade completamente testada em todos os ambientes aplicáveis, assegurando que os logs são gerados e armazenados corretamente.
- Revisão e aprovação.

**Comment by samiraetc** [comment]
assim que finalizarem essa tarefa, peço por favor que me mencionem pra que eu possa finalizar a parte do frontend

**Comment by diegodario88** [comment]
Olá, fiquei com uma dúvida com relação ao _item_. Qual entidade deve-se ouvir as atualizações para proceder com a escrita na tabela `item_updates_log`?

**Comment by giggio** [comment]
Estou fazendo esse item.

**Comment by giggio** [comment]
@rhuam Seria bom esclarecer, no banco de dados não há uma tabela de items, mas os itens são chamados de `supplies`. É isso que vamos manter o log? Recomendo o uso de `supplies_history` para a tabela.

**Comment by rhuam** [comment]
@risaddex pode só alterar o nome da tabela para **supplies_history**, por gentileza. Foi uma sugestão pertinente do @giggio  que ajuda a entender o que essa tabela armazena de fato.

**Comment by risaddex** [comment]
Pode me atribuir por gentileza, comecei a implementação.

**Comment by larissapissurno** [comment]
movendo para "Disponível para QA", pois foi movida automaticamente para "Done" ao mergear o PR
