### ISSUE TITLE
Abrir outro link do discord

### ISSUE THREAD

**Issue by mgrithm** [SOS-RS/backend#19]
Faça outro link do discord

**Comment by AndersonCRocha** [comment]
@MatheusDubin Onde ficam as informações do projeto? Discord, Trello e etc

**Comment by rhuam** [comment]
Atualmente o backlog está no trello e discursões no Discord. Estamos restruturação para aceitar mais membros de forma organizada.

**Comment by MatheusDubin** [comment]
Assim que finalizarmos isso eu atualizo aqui na issue mesmo!

**Comment by AwaitMark** [comment]
Fala mestre, estou querendo ajudar sou especialista js, entao Node é comigo mesmo, vocês vao disponibilizar o link do discord por aq mesmo, preciso ver o backlog, abraços!

**Comment by RafaelFrire** [comment]
Boa noite, senhores
Parabéns pela iniciativa, eu quero poder contribuir com vocês, por favor disponibilizem o novo link do discord para nos alinharmos, abraços!

**Comment by Ravelos** [comment]
Eu quero ajudar também

**Comment by FIRMINOenzo** [comment]
estou no aguardo também!

**Comment by M4rcxs** [comment]
Olá, alguém pode me enviar o Link do canal no Discord?

**Comment by lrnz-nabooki** [comment]
Se precisar ainda alguma ajuda no back-end eu também estou disponível, mas como mencionado pelo @Lacerda53  eu também prefiro discutir rapidamente com os envolvidos o que precisa ser realmente feito. Eu moro na Austrália então estaria trabalhando em horários diferentes, o que pode ser bom pra manter pra manter o time trabalhando 24/7 lol.

**Comment by MatheusDubin** [comment]
Bom dia, realizamos as alterações de onboarding, agora é só acessar por aqui:

https://discord.com/invite/QqA223Rr2P

Obrigado pela paciência!
