### ISSUE TITLE
Readme.md cita MongoDB, docker-compose e arquivos migration parecem SQL

### ISSUE THREAD

**Issue by fabianofa** [SOS-RS/backend#22]
É um erro de escrita, ou no deploy é usado Mongo de fato?

**Comment by AndersonCRocha** [comment]
Acredito que o readme está desatualizado, pois no arquivo de schema do prisma tbm está configurado para usar o postgreSQL

**Comment by rhuam** [comment]
É um erro no Readme. O banco é SQL (Postgres).

**Comment by mgrithm** [comment]
Falta só eu terminar o PR das audits logs e envio outro pra organizar o readme.

**Comment by filipepacheco** [comment]
corrigido. obrigado!
