### ISSUE TITLE
Algum dump do banco para teste?

### ISSUE THREAD

**Issue by cesarpastorini** [SOS-RS/backend#23]
Seria bem útil ter à mão alguns dados de teste para popular a banco de dados.

Alguém que tenha poderia compartilhar?

**Comment by Marcos9868** [comment]
O dump do banco de dados está no Discord, só pedir para o adm

**Comment by MatheusDubin** [comment]
Temos no discord https://discord.gg/SVvUYPp6! 
Só acessar ali e publicar no #apresentacão que te assignamos o papel de colaborador e tu tens accesso ;)
