### ISSUE TITLE
Sugestão: Adicionar link para rede social de civis dentro dos abrigos recebendo doações

### ISSUE THREAD

**Issue by Gabrielbbe** [SOS-RS/backend#27]
Alguns civis estão recebendo doações via pix e documentando o que estão fazendo nas redes sociais para ajudar os outros desabrigados com o dinheiro arrecadado, o que torna a doação mais direta e confiável, acredito que adicionar esses links na forma de uma lista dentro do projeto seria de grande valor para essas pessoas.

**Comment by lorenzofk** [comment]
Eu tinha criado uma aplicação simples pra centralizar todos os canais confiáveis de PIX e/ou vaquinhas, mas fiquei meio struggling pensando como fazer isso escalar de forma que vaquinhas/pix fraudulentos não sejam inseridos ou aprovados. Alguma ideia?
