### ISSUE TITLE
Provedores de Abrigos

### ISSUE THREAD

**Issue by DanielHe4rt** [SOS-RS/backend#3]
Salve meu querido! Existe alguma possibilidade de você abrir uma API pra consultar os abrigos pra que outras aplicações consumam? 

Vejo que está tendo multiplas fontes de dados e esse projeto poderia ser a principal entre todas. Facilitaria muito...

**Comment by romuloigor** [comment]
@DanielHe4rt acabei de criar o script python para consumir a API do SOS-RS, olha no https://mapa-das-doacoes.streamlit.app/

**Comment by MatheusDubin** [comment]
Fala @DanielHe4rt , é uma ótima ideia!

**Vamos conversar hoje entre os colaboradores aqui e aí te damos um retorno ASAP por aqui mesmo**, minha preocupação maior agora é introduzirmos breaking changes que podem afetar o seu consumo.

**Comment by Natalie9** [comment]
Uma preocupação que estou tendo é sobre diversas fontes de dados sendo geradas. Semelhante a esse projeto vi alguns outros como:
[AbrigaRS](https://www.linkedin.com/posts/daniela-yabe-12ba19b3_provavelmente-voc%C3%AA-j%C3%A1-viu-o-que-est%C3%A1-acontecendo-activity-7194353611831709696-uQA1?utm_source=share&utm_medium=member_desktop)
[Pelo Rio Grande SOS QR Code](https://peloriogrande.sosqrcode.com.br/) 
[Desabrigados](https://desabrigados.com.br/) 

E imagino que tenham alguns outros. Temos informação do uso na linha de frente, como está sendo a divulgação e feedbacks?

**Comment by MatheusDubin** [comment]
Dando um retorno aqui, estamos muito felizes com o uso da API para criação de outras visualizações que agregem no esofrço de ajuda!

@DanielHe4rt Vamos levar em consideração que a API está sendo consumida e evitarmos breaking changes, a menos que estritamente necessário. Dado que o quanto mais rápido conseguimos entregar funcionalidades, mais cedo ela poderá ser usada para ajudar pessoas, pode acontecer, mas iremos comunicar.

@Natalie9 Estamos trabalhando já hoje para realizar uma integração de dados com o AbrigoRS e estamos em contato com outras soluções, há questões de integridade de dados que complica essas integrações mas estamos tentando nosso máximo para resolve-las e centralizar as informações, muito obrigado por trazer essas soluções!
