### ISSUE TITLE
Listagem com a contagem geral de itens mais necessários

### ISSUE THREAD

**Issue by ujorgeleitessc** [SOS-RS/backend#38]
Amigos de minas gerais que estão mandando mantimentos tem a necessidade de saber a necessidade geral de itens mais necessários.

Por exemplo

1 Fralda tamanho M
2 Água galão 5 litros
3 chinelos tamanho 37/38

Mas isso em endpoint publico e de forma direta para que eles saiba direcionar a coleta!

**Comment by ujorgeleitessc** [comment]
@fagundesjg @maneljr

**Comment by daravahn** [comment]
pera gente, é um pouco diferente, explico no próximo comentário

**Comment by ricardodarocha** [comment]
> pera gente, é um pouco diferente, explico no próximo comentário

Cria nova issue, ou pede os organizadores para habilita o tópico de discussão
Pra mim é mais efetivo issue como um requisito pendente de implementar

O que acham

**Comment by ricardodarocha** [comment]
> Amigos de minas gerais que estão mandando mantimentos tem a necessidade de saber a necessidade geral de itens mais necessários.
> 
> Por exemplo
> 
> 1 Fralda tamanho M 2 Água galão 5 litros 3 chinelos tamanho 37/38
> 
> Mas isso em endpoint publico e de forma direta para que eles saiba direcionar a coleta!

Consegue especificar melhor o requisito? me ajude, Por exemplo


Oferecer um endpoint público /top10 com os dez itens mais exigidos, para saber a necessidade geral de itens por grau de necessidade. 

api/top10 

Respostas esperada
1 Fralda tamanho M
2 Água galão 5 litros
3 chinelos tamanho 37/38

Resposta no formato json
`json
{item: "Água galão 5 litros", 
quantidade: 2
}`

Obviamente que o endpoint pode possuir filtros, offset e vários outros parametros, porém deve ser avaliar o benefício disso já que poderia ocasionar um atraso na entrega

api/top/{:n}?{:skip}&{:regiao}

:n top 10 top 20 etc 
:skip indica a página inicial, default 0
:regiao string contem um argumento de filtro por nome do abrigo e ou região default "Todos"

**Comment by daravahn** [comment]
> > pera gente, é um pouco diferente, explico no próximo comentário
> 
> Cria nova issue, ou pede os organizadores para habilitar o tópico de discussão Pra mim é mais efetivo issue como um requisito pendente de implementar
> 
> O que acham

ficar fui eu que pedi pro @ujorgeleitessc criar a issue, só que ele ta na linha de frente ajudando com doações pra bebes e não consegue dar muita atenção aqui, eu to em MG e posso ajudar.

**Comment by daravahn** [comment]
já tem inclusive um mock do front gente! 

![image](https://github.com/SOS-RS/backend/assets/344350/44f47f70-9713-4556-8294-1c08d982c259)

usando essa resposta de referencia! json {item: "Água galão 5 litros",  quantidade: 2 }

**Comment by gmenti** [comment]
Fala pessoal, implementai a parte do front

A nova rota do back fiz pensando nesse formato abaixo, mas qualquer coisa posso mudar

GET https://api.sos-rs.com/supply/top10 com a resposta no seguinte formato:
{"data":[{"name": "Agua 5L", "amount": 10}, {"name": "Cobertor", "amount": 5}]}

**Comment by balsemao** [comment]
Pessoal, em minutinhos já mando o PR

**Comment by filipepacheco** [comment]
Ótima contribuição, galera!

Fechando a issue aqui pois implementamos em https://github.com/SOS-RS/backend/pull/50 !
Valeu!

**Comment by filipepacheco** [comment]
Pessoal, peço perdão. Acabei mencionando o PR errado.
Esse aqui é o PR correto: https://github.com/SOS-RS/backend/pull/29/files
