### ISSUE TITLE
Licença do repo

### ISSUE THREAD

**Issue by giggio** [SOS-RS/backend#40]
Seria uma boa colocar uma licença de software livre. Recomendo MIT, ou Apache2 em segundo lugar.

**Comment by filipepacheco** [comment]
ötima sugestão! implementado em https://github.com/SOS-RS/backend/pull/50

**Comment by giggio** [comment]
@filipepacheco o #50 ainda não foi mergeado.

**Comment by filipepacheco** [comment]
Será em breve. Valeu pela contribuição <3
