### ISSUE TITLE
Segurança das Informações.

### ISSUE THREAD

**Issue by guilhermeramos0603** [SOS-RS/backend#46]
Pessoal, sei que a intenção do app é ser rápido e simples para todos usarem. Mas todos poderem atualizar as infos dos abrigos acredito ser perigoso.

O que acha de fazermos um mini cadastro e a edição e criação de abrigos ser apenas uma solicitação, analisada e armazenada no Postgres e posteriormente aprovada por alguém.

Não da pra confiar em deixar totalmente aberto, infelizmente mesmo nessas horas pessoas agem de má fé.

**Comment by ricardodarocha** [comment]
Muito bem colocado @guilhermeramos0603 a segurança é muito importante , a segurança das informações, dos abrigados, dos profissionais de saúde etc. Seria importante criar um lastro de autenticidade de pessoas que estejam usando o sistema, principalmente para auditar os cadastros quando necessário. Vocês estão fazendo um registro de ips que acessam? Isso é o mínimo e já ajudaria a PF em casos críticos. 

Eu acho que algumas informações públicas podem ser úteis, conforme descrito na issue [38](issues/38), no entanto prevenir de compartilhar informações sensíveis como localização, nome de agentes, etc

**Comment by dgviero** [comment]
Olá pessoal!
Tive contato com uma pessoa responsável pela distribuição dos donativos aos abrigos e que está utilizando o app. 
Ela está com dificuldades para conseguir contato com o responsável pelo abrigo, pois muitos não tem essa informação. Teríamos que pensar alguma forma de deixar o dado seguro mas acessível a estas pessoas na linha de frente.

**Comment by filipepacheco** [comment]
Perfeito, pessoal. Ótimo tópico.

Hoje temos no nosso backlog a funcionalidade de edição apenas por pessoas autenticadas.
Obrigado pela discussão! Estamos aceitando sugestões e discussões no nosso Discord. https://discord.gg/u33fHExw

Vejo vocês lá
