### ISSUE TITLE
Converter campos created_at e updated_at de varchar para DateTime ou Timestamp no banco

### ISSUE THREAD

**Issue by filipepacheco** [SOS-RS/backend#53]
Hoje, no banco, nossas tabelas estão com as colunas `created_at` e `updated_at` como varchar.
Seria ideal transformarmos em datetime ou timestamp (a avaliar melhor opcão pro prisma) a fim de poder fazer consultas com lógica em volta desses campos.
É preciso também pensar na conversão desses dados.

**Comment by updev-sistemas** [comment]
Posso pegar essa atividade?
