### ISSUE TITLE
Sugestão: Lista de abrigados

### ISSUE THREAD

**Issue by newtonwagner** [SOS-RS/backend#7]
Saudações. Primeiramente parabéns pelo trabalho e dedicação. Tive a ideia de implementar uma lista de abrigados em cada abrigo, que facilitaria o reencontro e contato com suas famílias. Vi que criaram alguns canais no instagram, mas não sei se a plataforma facilita a busca.

Então, deixo aqui a sugestão caso queiram incluir no roadmap de vocês.
- Cadastrar abrigado (Nome obrigatório. CPF, Data de Nascimento/Idade opcionais [pra facilitar o cadastro]).
- Editar abrigado.
- Importar lista de abrigados (CSV).

**Comment by rhuam** [comment]
Infelizmente por questões legais e de segurança. Não seguiremos essa demanda. Agradeço a sugestão.
